name: autoupdate
on:
  # This will trigger on all pushes to all branches.
  push: {}

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    permissions: # Add explicit permissions
      contents: write # Grants write access to repository contents
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
